# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946f3e4f51a2773f9d9ef499b085ac73603b4edd443fefbf392f9b5e3b5640db9c3f50e60673ea4d47ab77c0f8fa0f7047cecf4ff3c48cfd6bccf926e6759be6

test:
  secret_key_base: bc796c8d2b5625c617e99a6a6566b16ee18964bad26f0e00d2923c459960dd5d67efbd701df54b09279ce6e75c68bdcd199e681bc5e4c3ecef99c69cfbb4effc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
